name: IBM_CF Reinstall V2ray

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 12 * * FRI'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        chmod -R 777 ./IBM_Cloud_CLI/
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
        REGION_NUM: ${{ secrets.REGION_NUM }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $REGION_NUM
        no
        EOF
    - name: Target IBM Cloud
      env:
        RESOURSE_ID: ${{ secrets.RESOURSE_ID }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID"
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install -v 6.51.0 -f
    - name: Restart IBM Cloud
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
        UUID: ${{ secrets.UUID }}
        WS_PATH: ${{ secrets.WS_PATH }}
      run: |
        cd ./v2ray-cloudfoundry/v2ray
        echo "已经进入V2ray目录，准备开始安装v2ray-cloudfoundry"
        pwd
        echo "对v2ray的可执行文件授予可编辑权限。"
        chmod 0755 ./*
        cd ..
        pwd
        echo "开始修改v2ray的配置文件。"
        cat >  ./manifest.yml  << EOF
        applications:
        - path: .
        name: ${IBM_APP_NAME}
        random-route: true
        memory: 256M
        EOF
        cat >  ./v2ray/config.json  << EOF
        {
            "inbounds": [
                {
                    "port": 8080,
                    "protocol": "vmess",
                    "settings": {
                        "clients": [
                            {
                                "id": "${UUID}",
                                "alterId": 4
                            }
                        ]
                    },
                    "streamSettings": {
                        "network":"ws",
                        "wsSettings": {
                            "path": "${WS_PATH}"
                        }
                    }
                }
            ],
            "outbounds": [
                {
                    "protocol": "freedom",
                    "settings": {}
                }
            ]
        }
        EOF
        echo "v2ray配置文件修改完成。。"
        cat ./v2ray/config.json
        echo "开始推送配置文件，进行远程部署!!"
        ../IBM_Cloud_CLI/ibmcloud cf push
        echo "配置完成。尽情享用~~~"
